name: Node

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - run: npm ci
      - run: npm run build
        env:
          DISABLE_ESLINT_PLUGIN: 'true'
          PUBLIC_URL: /${{ github.event.repository.name }}

      - uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: ./build
          single-commit: true
          silent: false

